### ISSUE TITLE
Different implementation of Quicksort

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/metrics#115]
I've found some sort implementations written in pure Lua - https://github.com/DarkRoku12/lua_sort (also you can take the tests here)

Could you check them, may be some of them could be a bit faster.

Also it will be great if you share some benchmarks shows that current approach is better than C-written.
(Without consideration that we drop C part and gcc requirement - it's obviously perfect)

_Originally posted by @olegrok in https://github.com/tarantool/metrics/pull/112#issuecomment-694688476_

**Comment by filonenko-mikhail** [comment]
Decreasing infonoise
