### ISSUE TITLE
Rename default metrics

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/metrics#117]
Prometheus have some problems with suffixes '_count' and '_total' for non-summary and non-histogram metrics

**Comment by vasiliy-t** [comment]
![image](https://user-images.githubusercontent.com/4940266/93651886-ba025f00-fa1b-11ea-84ca-e1bad7bfde5f.png)

**Comment by ZolotarevIgor-mail-ru** [comment]
https://gitlab.cncf.ci/prometheus/prometheus/commit/1faf33acacd28161ef8019e6beac68a10e524bfb
