### ISSUE TITLE
Expose full list of default metrics in documentation and make metrics descriptions more helpful

### ISSUE THREAD

**Issue by akudiyar** [tarantool/metrics#122]
Currently the metrics descriptions are very narrow, for example:

```
    utils.set_gauge('fiber_count', 'Amount of fibers', fibers)
    utils.set_gauge('fiber_csw', 'Fibers csw', csws)
    utils.set_gauge('fiber_memalloc', 'Fibers memalloc', falloc)
    utils.set_gauge('fiber_memused', 'Fibers memused', fused)
```

These descriptions aren't helping when the full list of metrics is received, there is no explanation of how to use them.

I suggest adding more detailed descriptions including recommendations of using the particular metrics for monitoring and expose the full list of default metrics as a reference in the module documentation.

**Comment by vasiliy-t** [comment]
@akudiyar https://www.tarantool.io/ru/doc/latest/book/monitoring/metrics_reference/
