### ISSUE TITLE
Configure metrics role without clusterwide config

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/metrics#132]
Allow to reconfigure `/metrics` endpoint e.g. `require('cartridge.metrics').init('/mymetrics')`

like in https://github.com/tarantool/migrations/blob/master/migrator/init.lua#L126

**Comment by ZolotarevIgor-mail-ru** [comment]
I propose to reconfigure it this way like in config:
```lua
require('cartridge.metrics').set_export({
{path='/metrics-json', format='json'}, 
{path='/metrics-prometheus', format='prometheus'}
}) 
```
