### ISSUE TITLE
Add deprecation notes to stat, graphite, prometheus.

### ISSUE THREAD

**Issue by sharonovd** [tarantool/metrics#16]
Since metrics now combines the power of above-mentioned modules, it is safe to add a deprecation note to each of them.

**Comment by vanyarock01** [comment]
- [ ] [stat PR](https://github.com/tarantool/stat/pull/27)
- [ ] [prometheus PR](https://github.com/tarantool/prometheus/pull/14)
- [ ] [graphite PR](https://github.com/tarantool/graphite/pull/4)

**Comment by ASverdlov** [comment]
Merged all three.
