### ISSUE TITLE
calculation of http_server_request_latency 

### ISSUE THREAD

**Issue by erachenko23** [tarantool/metrics#165]
Tarantool: 1.10.7.44
Mertics: 0.5.0

We trying build dashboad with tarantool responce latency based on http_server_request_latency metrics.
Output example:

http_server_request_latency{path="/v1/cache/free/get",method="POST",alias="master",status="200",quantile="0.5"} 0.20221914281137
http_server_request_latency{path="/v1/cache/free/get",method="POST",alias="master",status="200",quantile="0.9"} 2.5367430280894
http_server_request_latency{path="/v1/cache/free/get",method="POST",alias="master",status="200",quantile="0.99"} 20.854850088013

Over all day we dont see changing of quantile=0.99 value, value about ~20 second. We check tarantool logs for this endpoint and dont find requests with so slow responce. We tried to measure the response time of this method using http sniffer (elk) and build chart with 50, 90 and 99 pernentiles for compare.

![image](https://user-images.githubusercontent.com/43468129/103087390-5f6b3700-45f8-11eb-9c42-89cde4a44b11.png)

Why are the quantile values not changing? For what time interval are they calculated?

Thank you!

**Comment by seet61** [comment]
It's actual bug

**Comment by seet61** [comment]
It's actual bug
