### ISSUE TITLE
Community chat report

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/metrics#171]
> так же еще столкнулись с ошибкой
Instance entering failed state: ConfiguringRoles -> OperationError#012ApplyConfigError: ...unter/.rocks/share/tarantool/cartridge/roles/metrics.lua:83: attempt to index local 'httpd' (a nil value)...
но ее пофиксили самостоятельно. пришлось включить httpd модуль в инстансе стораджа. без этого с включенными метриками не работало

**Comment by ZolotarevIgor-mail-ru** [comment]
https://github.com/tarantool/cartridge/issues/551

**Comment by ZolotarevIgor-mail-ru** [comment]
Fixed in https://github.com/tarantool/cartridge/releases/tag/2.5.0
