### ISSUE TITLE
Rework histogram buckets process

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/metrics#196]
`ipairs` should be there if we want to check up if array is sorted, not `pairs`
https://github.com/tarantool/metrics/blob/a2d783e5b68475a7c88f89b5ea10ce470d8e67fa/metrics/collectors/histogram.lua#L12

**Comment by orchaton** [comment]
Debatable! `pairs` actually iterates through numeric part firstly (like `ipairs` does), and only then iterate through keys. You may replace `pairs` with `ipairs` only when you manage to guarantee that table buckets contains only numeric part.
```lua
for k, v in pairs(buckets) do
        if type(k) ~= 'number' then return false end
        if type(v) ~= 'number' then return false end
        if v <= 0 then return false end
        if prev > v then return false end
        prev = v
end
```

**Comment by DifferentialOrange** [comment]
> Debatable! `pairs` actually iterates through numeric part firstly (like `ipairs` does), and only then iterate through keys. You may replace `pairs` with `ipairs` only when you manage to guarantee that table buckets contains only numeric part.
> 
> ```lua
> for k, v in pairs(buckets) do
>         if type(k) ~= 'number' then return false end
>         if type(v) ~= 'number' then return false end
>         if v <= 0 then return false end
>         if prev > v then return false end
>         prev = v
> end
> ```

Lua documentation states that 

> The pairs function, which iterates over all elements in a table, is similar [to ipairs], except that the iterator function is the next function
> The call next(t, k), where k is a key of the table t, returns a next key in the table, in an **arbitrary** order.
