### ISSUE TITLE
Lack of Documentation for default_metrics

### ISSUE THREAD

**Issue by maiabdelqader** [tarantool/metrics#20]
I enabled default metrics for Prometheus, however, the documentation for these metrics is poor and hasn't full information.

**Comment by DifferentialOrange** [comment]
README descriptions says

> Collects tarantool metrics, ported from https://github.com/tarantool/stat

and nothing about what particular default metrics we have. Moreover, deprecated `stat` module also don't have default metrics list, and its example has both default metrics and metrics which we don't collect by default in the current version of `metrics`.

The most convenient way to get thorough list of default metrics is to build an app and collect them, which seems weird to me. Alternatively, we need to scroll through 11 source files of `default_metrics/tarantool` folder.

I suggest that we should add at least a list of default metrics to README or another docs source. (But a list with a short descriptions will be even a better idea.)

**Comment by DifferentialOrange** [comment]
Refer to #78

**Comment by vasiliy-t** [comment]
closing in favour of #78
