### ISSUE TITLE
Добавить в метрики статус репликации

### ISSUE THREAD

**Issue by dsamirov** [tarantool/metrics#203]
Сейчас в репликационных метриках есть `lsn` и `lag`.

По ним в теории можно косвенно понять о том, что репликация сломалась, но для пользователя было бы понятнее, если бы была доступна отдельная метрика `status`, которая берется из `box.info.replication`.

**Comment by no1seman** [comment]
кажется надо делать не один статус, а несколько: для downstream-ов и upstream-ов

**Comment by DLukovkin** [comment]
A very good idea! Replication status, like all replication metrics, is extremely important.
