### ISSUE TITLE
Huge memory consumption of "Shared.make_key" function

### ISSUE THREAD

**Issue by olegrok** [tarantool/metrics#204]
Recently I run my project under memprof.
Results show that "Shared.make_key" consumes huge amount of memory.

```
@/Users/o.babin/Projects/tdg/.rocks/share/tarantool/metrics/collectors/shared.lua:42, line 45: 7408397
  177807041       0
@/Users/o.babin/Projects/tdg/.rocks/share/tarantool/metrics/collectors/shared.lua:42, line 43: 7407732
  474094848       0
```

It's the third place in top after JSON parsing and graphql execution. I suggest to optimize this place anyhow. Seems the root of problem is "histogram.observe" usage.

**Comment by filonenko-mikhail** [comment]
It requires to rewrite metrics arch, so it's not so easy right now. Very gently closing to decrease infonoise.
