### ISSUE TITLE
Make metrics config more flexible

### ISSUE THREAD

**Issue by no1seman** [tarantool/metrics#222]
Let's divide all metrics to groups(classes) and make it possible to select which metrics turned on. Also if no any settings was set simply turn on default metrics groups(classes). Groups could be configurable with set_export() or Cartridge Role config.

Reason: each metric occupy some space in Prometheus or InfluxDB and for example not every application uses http, in that case don't need to collect tnt_http_* metrics.

**Comment by DifferentialOrange** [comment]
Btw, if you don't use HTTP metrics in your app (i.e. do not set any HTTP middleware on any endpoints) there isn't any `http_` metrics in Tarantool default metrics.
