### ISSUE TITLE
Not working with package.reload

### ISSUE THREAD

**Issue by TvoroG** [tarantool/metrics#228]
`metrics==0.8.0`
```
> package.reload()

sentry_error: ...hare/tarantool/metrics/default_metrics/tarantool/cpu.lua:18: attempt to redefine 'timeval'
```

**Comment by TvoroG** [comment]
How do you reload your app? Is `package.reload` obsolete?

**Comment by ZolotarevIgor-mail-ru** [comment]
@zwirec

**Comment by no1seman** [comment]
Also doesn't work with cartridge.reload_roles():
- null
- line: 18
  class_name: ApplyConfigError
  err: '...hare/tarantool/metrics/default_metrics/tarantool/cpu.lua:18: attempt to
    redefine ''timeval'''
  file: '...hare/tarantool/metrics/default_metrics/tarantool/cpu.lua'
  stack: "stack traceback:\n\t...hare/tarantool/metrics/default_metrics/tarantool/cpu.lua:18:
    in main chunk\n\t[C]: in function 'require'\n\t...are/tarantool/metrics/default_metrics/tarantool/init.lua:14:
    in main chunk\n\t[C]: in function 'require'\n\t...ru/app-cartridge/.rocks/share/tarantool/metrics/init.lua:97:
    in function 'enable_default_metrics'\n\t...ridge/.rocks/share/tarantool/cartridge/roles/metrics.lua:35:       
    in function <...ridge/.rocks/share/tarantool/cartridge/roles/metrics.lua:33>\n\t[C]:
    in function 'xpcall'\n\t...r/mailru/app-cartridge/.rocks/share/tarantool/errors.lua:145:
    in function 'pcall'\n\t...app-cartridge/.rocks/share/tarantool/cartridge/roles.lua:351:
    in function 'apply_config'\n\t...rtridge/.rocks/share/tarantool/cartridge/confapplier.lua:252:
    in function <...rtridge/.rocks/share/tarantool/cartridge/confapplier.lua:221>\n\t[C]:
    in function 'pcall'\n\tbuiltin/box/console.lua:56: in function <builtin/box/console.lua:39>\n\t[string        
    \"local function func(...) return require('cons...\"]:1: in main chunk\n\t[C]:
    in function 'pcall'\n\tbuiltin/box/console.lua:56: in function 'eval'\n\tbuiltin/box/console.lua:291:
    in function 'repl'\n\tbuiltin/box/console.lua:442: in function <builtin/box/console.lua:428>\n\t[C]:
    in function 'pcall'\n\tbuiltin/socket.lua:1058: in function <builtin/socket.lua:1056>"
  str: 'ApplyConfigError: ...hare/tarantool/metrics/default_metrics/tarantool/cpu.lua:18:
    attempt to redefine ''timeval'''
Affected versions: 0.8.0 while 0.7.1 works fine
