### ISSUE TITLE
cartridge role should rollback config changes in case if section removed

### ISSUE THREAD

**Issue by olegrok** [tarantool/metrics#234]
Consider a case:
  - I use metrics.set_export({\_\_first_case__}) -> "first case" works
  - Then I apply config with metrics.export section with "second case" -> "second case" works
  - When I remove "metrics" section from config at all.

https://github.com/tarantool/metrics/blob/35984c082db169ed8c82104d1a49e5b24fdb2f36/cartridge/roles/metrics.lua#L119-L121

  - "second case" still works (but until the first instance restart - it's an inconsistency)
  - Expected "first case" works

**Comment by opomuc** [comment]
@olegrok 
> Expected "first case" works

what do you mean by that? you have reapplied config with a new endpoint and you want old one to work?

**Comment by olegrok** [comment]
> what do you mean by that? you have reapplied config with a new endpoint and you want old one to work?

I consider set_export as default for "cluster-wide config" settings. After I remove section from cluster-wide config I expect default will work.
Also I expect consistency. Above I wrote that after "metrics" section was removed it still worked. But it's not consistent - if server will restarted (manually or because of crash) instance won't expose metrics anymore.

**Comment by opomuc** [comment]
> I consider set_export as default for "cluster-wide config" settings. After I remove section from cluster-wide config I expect default will work.

I don't think we should consider set_export a default. And expect an implicit return to old configuration after we removed metrics section in config. If you remove it -- no metrics. 

> Also I expect consistency. Above I wrote that after "metrics" section was removed it still worked. But it's not consistent - if server will restarted (manually or because of crash) instance won't expose metrics anymore.

This I understand and agree.

**Comment by yngvar-antonsson** [comment]
Seems it's closed by #257
