### ISSUE TITLE
Customizable health response

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/metrics#242]
We have some requirements from our customer to set up a health check. But this health check should be consistent with current customer infrastructure. He expects something like this
```lua
{
    ["service.name"] = "our-app",
    ["service.status"] = 1,
    alias = 'instance-1',
}
```
if instance if healthy and code 500 if it is not.

It would be convenient to be able to set up custom health output. At least we can make `cluster.is_healthy` an external function which returns something like `true` or `false` and can be `require`d in code so we can build custom HTTP handle for healthcheck. It would be even better if we would be able to set this handle with clusterwide config and `metrics.set_export` (related to #120).

**Comment by rosik** [comment]
I don't like this feature request. The thing you're asking for is actually `httpd:route('/health')`. It's not related to the metrics module. You can already do it in several different ways:

- straight-forward in `init.lua`
- by creating a custom cartridge role
- using https://github.com/tarantool/cartridge-extensions.

This comment also applies to #120. Please, consider closing them both.

**Comment by yngvar-antonsson** [comment]
Closed because of https://github.com/tarantool/metrics/issues/242#issuecomment-890057341
