### ISSUE TITLE
Don't create a counter if it already exists

### ISSUE THREAD

**Issue by knazarov** [tarantool/metrics#27]
Currently if you do this:

```lua
local counter = metrics.counter('foobar')
```

Then it creates a new counter object every time. This means that users have to store counter objects carefully.

What I propose is to make such calls idemponent: if the parameters (like histogram buckets etc) don't change -- then just return an existing counter.

**Comment by filonenko-mikhail** [comment]
lgtm

**Comment by olegrok** [comment]
May be it's better to introduce `if_not_exists` option?

**Comment by knazarov** [comment]
@olegrok I don't see any value in replacing the existing counter object by default.

**Comment by olegrok** [comment]
> @olegrok I don't see any value in replacing the existing counter object by default.

Ok, I don't have a strong arguments against it - LGTM

**Comment by dimoffon** [comment]
Created pr https://github.com/tarantool/metrics/pull/28
