### ISSUE TITLE
Add master/slave history (faliover) metric

### ISSUE THREAD

**Issue by no1seman** [tarantool/metrics#275]
It wiil be great to add one simple metric that will return box.info.ro==false => 1 box.info.ro== true> 0 on each metrics scrape. This will give us an option to draw a graph of history of master switching over all instances of cluster and then we can easily filter instances by replicasets (may be for this only metric add replicaset alias label for Cartridge apps and replicaset UUID for non-Cartridge ones?).

**Comment by opomuc** [comment]
What if we had multiple changes inside `scrape_interval`? It will not affect graphs, but can influence an application

**Comment by no1seman** [comment]
Well it's not a problem to set a trigger on box.ctl.wait_ro()/box.ctl.wait_rw() but I have no any ideas of how to graph that info without dramatic coplexity. Have you?
