### ISSUE TITLE
Increase default collector precision

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/metrics#301]
HTTP request process time is Tarantool is mostly <10μs since Tarantool is designed to be fast. At the same time, default summary collector quantile tolerance is 10ms:

https://github.com/tarantool/metrics/blob/df62af8fb3f1ee4b65893349ae6e8c6eb95d38a9/metrics/http_middleware.lua#L11-L15

I think the case when 10 ms tolerance is fine is 100ms-latency requests. It is not common for Tarantool. So to get nice results in graphs one must set up quantiles manually each time and default summary collector seems useless in this case.

So I think it would be for the better to decrease tolerance threshold in default summary HTTP collector.

**Comment by yngvar-antonsson** [comment]
epsilon is a relative error, so 0.01 (= 1%) is enough. Closed. 
![telegram-cloud-photo-size-2-5345856819244940517-x](https://user-images.githubusercontent.com/63460867/147355260-d685b01a-46ba-4f18-a80e-af91e8b05a3b.jpg)
