### ISSUE TITLE
Add a pseudo proxy feature to the metrics module.

### ISSUE THREAD

**Issue by DLukovkin** [tarantool/metrics#302]
Now, in order to get metrics from an instance, you need to run the http module on a specific port for each instance. Which is very inconvenient with a large number of servers and instances on them. It would be nice to make it possible to run one http module on some one port for all server instances. At the same time, each individual instance could be distinguished by custom labels or by the value of the box.cfg.listen section in the instance configuration.

**Comment by rosik** [comment]
It's easy to do without any new features. You can use `require('metrics').collect()`. Call it over net.box (`cartridge pool.map_call` can help with that) or with your language connector.

**Comment by DLukovkin** [comment]
But what if we don't use cartrige?
How prometheus will collect data via netbox connect?
In any case, a pseudo proxy will be useful to many users.

**Comment by yngvar-antonsson** [comment]
It's not a scope of metrics/http modules.
You could implement it as a custom logic:
1) create one instance for metrics aggregation and enable http on it
2) iterate over other instances with `net_box.eval` / `net_box.call` and call `metrics.collect()` on them
3) aggregate answers from instances and export them to a `/metrics` endpoint in Prometheus format
