### ISSUE TITLE
Summary quantiles respond +Inf if rps decreases to zero

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/metrics#303]
If there are 0 new requests for some time, summary collector quantiles respond with +Inf values.

![image](https://user-images.githubusercontent.com/20455996/133574070-4852375b-689a-47af-ba0f-4d352077baa0.png)
 
 ```
http_server_request_latency{path="/hello",method="GET",alias="tnt_router",status="200",quantile="0.5"} +Inf
http_server_request_latency{path="/hello",method="GET",alias="tnt_router",status="200",quantile="0.9"} +Inf
http_server_request_latency{path="/hello",method="GET",alias="tnt_router",status="200",quantile="0.99"} +Inf
http_server_request_latency{path="/goodbye",method="POST",alias="tnt_router",status="500",quantile="0.5"} +Inf
http_server_request_latency{path="/goodbye",method="POST",alias="tnt_router",status="500",quantile="0.9"} +Inf
http_server_request_latency{path="/goodbye",method="POST",alias="tnt_router",status="500",quantile="0.99"} +Inf
http_server_request_latency{path="/hell0",method="GET",alias="tnt_router",status="400",quantile="0.5"} +Inf
http_server_request_latency{path="/hell0",method="GET",alias="tnt_router",status="400",quantile="0.9"} +Inf
http_server_request_latency{path="/hell0",method="GET",alias="tnt_router",status="400",quantile="0.99"} +Inf
 ```
 
It breaks visualization with ugly vertical lines. I'm sure there are better approaches to handle this.

### Reproducer

You may use https://github.com/tarantool/grafana-dashboard docker cluster and stop load container after several minutes.
```bash
docker-compose up
# let it generate some metrics
docker stop grafana-dashboard_load_generator_1
```

**Comment by yngvar-antonsson** [comment]
Now it's a part of the quantile algorithm and covers with tests:

https://github.com/tarantool/metrics/blob/7652824a1a08c40fb98cd755bf32c8378a1b4362/test/quantile_test.lua#L144

We could convert values from empty quantile collector to `null`.

**Comment by DifferentialOrange** [comment]
> Now it's a part of the quantile algorithm and covers with tests:
> 
> https://github.com/tarantool/metrics/blob/7652824a1a08c40fb98cd755bf32c8378a1b4362/test/quantile_test.lua#L144
> 
> We could convert values from empty quantile collector to `null`.

I think it is a good idea

**Comment by yngvar-antonsson** [comment]
https://github.com/tarantool/metrics/blob/7652824a1a08c40fb98cd755bf32c8378a1b4362/metrics/quantile.lua#L158

```lua
if s[1] == math.huge then
  return nil
end
```
