### ISSUE TITLE
Add default collector for lua functions

### ISSUE THREAD

**Issue by no1seman** [tarantool/metrics#314]
As for now module have quite powerfull default_http_collector which makes http metrics turning on in a few lines of code. But http - is not the only one interface middleware can connect to Tarantool. So, it will be great to add some sort of wrapper-helper and initialisation helper to make it possible to collect call counter, average executon time and latency percentiles in a few lines of code.

Possible interface wiil be the following:

- Initialiser: metrics.register_callback(metrics.func_middleware.callback)
- Wrapper: wrapper(fn, fn_name, opts) where:
fn - function which metrics to be collected
fn_name  - custom name of metric
opts - some options, for example flags to choose which metrics to collect, all by default.

**Comment by sharonovd** [comment]
requested by customer

**Comment by filonenko-mikhail** [comment]
Is someone make some thing in his usercode ?

**Comment by filonenko-mikhail** [comment]
So, no plans today. Feel free to reopen.
