### ISSUE TITLE
Provide a way to check version in code

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/metrics#330]
`metrics` is a developing package and new features or critical bugfixes happen often, as well as new releases. There are no explicit way to check what metrics version is used in code when you are providing an optional integration with your module. For example, the only way to check that I'm using metrics `0.9.0` or greater with age buckets and fixed summary under high load is to check `require('metrics.collectors.summary').rotate_age_buckets ~= nil`, but this check is based on internal structure of the module that could change at any time. It would be nice to have something like `require('cartridge.VERSION')`.

**Comment by yngvar-antonsson** [comment]
I think it should be done with #24

**Comment by Totktonada** [comment]
Similar to https://github.com/tarantool/graphql/issues/29.

**Comment by yngvar-antonsson** [comment]
We could use this script:
https://github.com/tarantool/graphqlide/blob/master/scripts/release.sh

**Comment by DifferentialOrange** [comment]
🤔
