### ISSUE TITLE
Reset callbacks when Cartridge roles hot reload

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/metrics#378]
After [#341 ](https://github.com/tarantool/metrics/pull/341) callbacks don't reset too. It seems like an unexpected behavior.

At least with cartridge, because each:
```
myapp.router> require("cartridge.roles").reload()
myapp.router> metrics = require("metrics")
```
adds 16 callbacks to:

https://github.com/tarantool/metrics/blob/b17a3234daff03481d15efa9a0c24e0cf56888ed/metrics/registry.lua#L13

16, 32, 48...

Old callbacks may be outdated or use outdated data. If we call them, it can lead to unexpected errors.

**Comment by filonenko-mikhail** [comment]
Let's reset callbacks
