### ISSUE TITLE
Гипотеза добавление новой базы с метриками

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/metrics#414]
У кастомера для обработки метрик есть продукт Ключ Астром. Происследовать возможности отправки метрик в эту систему.

**Comment by yngvar-antonsson** [comment]
https://doc.ruscomtech.ru/index.php/Метрики_Prometheus#.D0.A0.D0.B5.D0.BA.D0.BE.D0.BC.D0.B5.D0.BD.D0.B4.D1.83.D0.B5.D1.82.D1.81.D1.8F.2C_.D0.B5.D1.81.D0.BB.D0.B8_.D1.83_.D0.B2.D0.B0.D1.81_.D0.B5.D1.81.D1.82.D1.8C_.D0.BF.D0.BE.D0.BB.D0.BD.D1.8B.D0.B9_.D0.BA.D0.BE.D0.BD.D1.82.D1.80.D0.BE.D0.BB.D1.8C



> Текущие ограничения интеграции метрик Prometheus следующие:
> Эта интеграция поддерживает только метрические типы Prometheus **счетчиков и датчиков**.
> Если вы запускаете несколько экспортеров в модуле, вам необходимо настроить metrics.{server-name}.com/portаннотацию, чтобы направить Ключ-АСТРОМ к той, которую она должна использовать.
> Эта интеграция поддерживает до **1000 модулей с 200 метрическими точками данных в минуту**.

Поддерживаются метрики в Prometheus-формате, но только counter и gauge
