### ISSUE TITLE
Incorrect handling of cdata values

### ISSUE THREAD

**Issue by olegrok** [tarantool/metrics#480]
Implicitly we add "inf" bucket to histogram:

https://github.com/tarantool/metrics/blob/d239e851471d3e98a9b23b6949c140c6a346b031/metrics/collectors/histogram.lua#L27-L29

Then we allow to observe any value that can be casted to number: numbers, strings (like "1", "2", "3") and ULL/LL cdata.

But this condition doesn't consider value type anyhow:
https://github.com/tarantool/metrics/blob/d239e851471d3e98a9b23b6949c140c6a346b031/metrics/collectors/histogram.lua#L58

In case of string it just throws:
```
tarantool> mutation_time:observe('1')
---
- error: '.../share/tarantool/override/metrics/collectors/counter.lua:9: attempt to
    compare string with number'
...
```

In case of cdata in incorrectly compares input value with `inf`:
```
tarantool> mutation_time:observe(1ULL)
-- input - bucket - [input < bucket]
1ULL	100	true
1ULL	200	true
1ULL	300	true
1ULL	400	true
1ULL	500	true
1ULL	600	true
1ULL	700	true
1ULL	800	true
1ULL	900	true
1ULL	1000	true
1ULL	inf	false
```

It's caused by LuaJIT semantics:
```
tarantool> inf = 1/0
---
...

tarantool> inf > 1
---
- true
...

tarantool> inf > 1ULL
---
- false
...

tarantool> inf > 1LL
---
- false
...
tarantool> tonumber('inf') == 0ULL
---
- true
...
```

It's very hard to find an issue with cdata numbers. I suggest to throw in such cases or signal about an issue somehow.

**Comment by yngvar-antonsson** [comment]
So, why can't we use `tonumber`? It might fix the related `tdg` ticket. What's your concern about it?
I'm ok with any solution here, but throwing an error will cause additional logic in TDG.

**Comment by olegrok** [comment]
> What's your concern about it?

It's one of solutions. My concern that tonumber(cdata) can cause precision loss. It's not relevant for my case, but it's possible.
Some implicit transformation can still lead to some inconsistencies. But in case we make user to pass explicit number it's not our responsibility to care about that.
