### ISSUE TITLE
cartridge metrics

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/metrics#80]
We could collect such metrics as:

1. We could add new metric ```issues_count``` of type gauge. Value is a number of cluster issues this instance knows. This should be good enough for basic alerting - healthy cluster reports 0 issues. - closed in #243 and #144 
2. Cartridge instance state (like OperationError) as numerical value -- needs design
3. ~~Time since last restart~~ - already present as metric `tnt_info_uptime`
4. Failover trigger count -- could be transformed from metric `tnt_read_only`, but needs desing too

**Comment by opomuc** [comment]
This has been started in https://github.com/tarantool/metrics/commit/4f4917de7bbae52c756aafeb201d8331f0ff0fde and released under [v0.6.0](https://github.com/tarantool/metrics/releases/tag/0.6.0).

I will close it for now. Feel free to reopen or create a separate issue regarding new metrics in cartridge.

**Comment by ZolotarevIgor-mail-ru** [comment]
Reopen with 3 new metric.

**Comment by opomuc** [comment]
Those are new metrics

1. Cartridge instance state (like OperationError) as numerical value
1. Time since last restart
1. Failover trigger count

**Comment by rosik** [comment]
Design draft. We've discussed making it a part of cartridge. It would be easier to maintain the list.

```lua
local state_numeric_const = {
    [''] = 0,
    ['Unconfigured'] = 10,
    ['ConfigFound'] = 11,
    ['ConfigLoaded'] = 12,

    ['BootstrappingBox'] = 20,
    ['RecoveringSnapshot'] = 21,

    ['ConnectingFullmesh'] = 30,

    ['BoxConfigured'] = 40,

    ['ConfiguringRoles'] = 50,
    ['RolesConfigured'] = 51,

    ['ReloadingRoles'] = 60,

    ['InitError'] = 90,
    ['BootError'] = 91,
    ['OperationError'] = 92,
    ['ReloadError'] = 93,
}

for state, _ in pairs(state_transitions) do
    if state_numeric_const[state] == nil then
        error(string.format('Missing numeric const for %q', state))
    end
end
```

**Comment by yngvar-antonsson** [comment]
Closed until someone would need those metrics. Feel free to reopen.
