### ISSUE TITLE
Average collector breaks Prometheus plugin

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/metrics#92]
The only types supported by Prometheus are Gauge, Counter, Histogram and Summary ([docs](https://prometheus.io/docs/concepts/metric_types/)):
![image](https://user-images.githubusercontent.com/20455996/88040313-62499380-cb51-11ea-874a-40d5da5b5cce.png)

**Comment by DifferentialOrange** [comment]
I propose to use [`Summary`](https://prometheus.io/docs/practices/histograms/) instead of average. It has similar structure and meaning.

But I'm not sure that it could be used in InfluxDB in the same way it used now (with Summary average value should be computed on datasource's side instead of Tarantool's side).

**Comment by DifferentialOrange** [comment]
I see two possible solutions to this.

Our Average collector consists of four counters: total sum, total count, total sum on previous collect call, total count on previous collect call. On _collect_ call it computes average value and responses with avg and count values.

Simple (without quantiles support) Summary collector should respond with total sum and total count.

**1st solution:** rework Average _collect_ to support flag `export_as_summary` to respond with total sum and total count metrics, rework Prometheus _collect_and_serialize_ to call collect with that flag (other collectors' _collect_ methods will ignore it) and rename Average collector in HTTP response to Summary.

**2nd solution:** rework Average collector to be a Summary collector (but do not change its internal structure), support flag `export_as_average` in collector's _collect_ method and use it in Json _export_ so current Json behavior will not change.

I like the 2nd more because other "metrics" collectors (counter, gauge, histogram) are the same as corresponding Prometheus collectors and this change will require less hacks.

**Comment by vasiliy-t** [comment]
@DifferentialOrange Average collector is deprecated now, use Summary collector instead. resolved in #101
