### ISSUE TITLE
Add doc for ``average`` collector

### ISSUE THREAD

**Issue by Satbek** [tarantool/metrics#94]
there is no description about what is it and how it works
```
Average
Can be used only as a collector for HTTP statistics (described below) and cannot be built explicitly.```

**Comment by DifferentialOrange** [comment]
There was a short description on `collect` method API [in previous README version](https://github.com/tarantool/metrics/blob/baa4ffc94024ea0e9f14cbf538b4dbcd6e876408/README.md).

**Comment by vasiliy-t** [comment]
@Satbek Average collector is deprecated because it is not compatible with prometheus. Use Summary collector instead.
