### ISSUE TITLE
WIP: Summary collector

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/metrics#97]
Recently we introduced http middleware to instrument http server metrics and new collector type average. Average collector is not compatible with prometheus API and could be replaced with Summary collector. 

Affects:
- https://github.com/tarantool/metrics/issues/95
- https://github.com/tarantool/metrics/issues/94
- https://github.com/tarantool/metrics/issues/92

**Comment by vasiliy-t** [comment]
Summary collector has built in quantiles. prometheus go client calculates quantiles with https://github.com/bmizerany/perks/ we could use the very same algorithm

**Comment by knazarov** [comment]
I've tried to read a paper on calculating quantiles on unbounded time series. It was very complex.
Does this implementation do it simpler?

**Comment by vasiliy-t** [comment]
Yeap. The paper algorithm based on is pretty complex to read but the implementation in code is a straightforward: 
1. use sorted array to store observations
2. compress (throw out) observations whenever the number of observations is high 
3. store some additional fields to "compensate" the compression

Here is a good explanation of algorithm http://alexandrutopliceanu.ro/post/targeted-quantiles/ and improved version http://dimacs.rutgers.edu/~graham/pubs/papers/bq-pods.pdf

**Comment by vasiliy-t** [comment]
resolved in #101
